/**
 * Generated by FITpro Fixture Generator
 */
package Fixtures.client;

import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

import Teacher.SetUpTaskController;
import Teacher.UploadTaskController;
import application.QueryController;
import fit.ActionFixture;

/*
 * TODO: modify class to match the FIT test - edit and add methods as required.
 */
public class CreateNewAssignment extends ActionFixture {
	SetUpTaskController controllerTest;
	UploadTaskController nextControllerTest;
	private String teacherID;
	private String semID;
	private String choseDate;
	private String task;
	private String IDsem;
	private String fileName;
	
	public void setSemID(String IDsem){
		this.IDsem = IDsem;
	}
	
	public void setTask(String task) {
		this.task = task;
	}
	
	public void setDate(String choseDate) {
		this.choseDate = choseDate;
	}
	
	public void setTeacherID(String teacherID) {
		this.teacherID = teacherID;
	}
  
	public void setSemeID(String semID) {
		this.semID = semID;
	}
	
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}
	
	public String isCourseExist() {
		return String.valueOf(controllerTest.isCourseExist(teacherID,semID));
	}
	
	public void setDate(){
		nextControllerTest.setDate(null);
	}
	
	public String isDateSetted(){
		return String.valueOf(nextControllerTest.isDateSetted());
	}
	
	public String isUploadSucceded(){
		DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
		String date = choseDate;
		//convert String to LocalDate
		LocalDate localDate = LocalDate.parse(date, formatter);
		return String.valueOf(nextControllerTest.isUploadSucceded(localDate,task,IDsem,"1",fileName));
	}
	
	public void startController() {
		try {
			QueryController.connect("localhost", 5555);
		} catch (IOException e) {
			e.printStackTrace();
		}
		controllerTest = new SetUpTaskController("ControllerTestID");
		controllerTest.isNotTest = false;
	}
	
	public void startNextController(String courseID) {
		nextControllerTest = new UploadTaskController("ControllerTestID");
		nextControllerTest.isNotTest = false;
		nextControllerTest.setCourseID(courseID);//set current course id.
	}
}