


/**
 * Generated by FITpro Fixture Generator
 */
package Fixtures.client;

import java.io.IOException;

import SystemManager.SystemManagerAddCourseController;
import application.QueryController;
import fit.ActionFixture;

/*
 * TODO: modify class to match the FIT test - edit and add methods as required.
 */
public class DefineCourse extends ActionFixture {
	SystemManagerAddCourseController controllerTest;
	private String TeachingUnit;
	private String nameCourse;
	private String Hours;
	public static boolean isNotTest = false;
	
	public void setHours(String setHours) {
		this.Hours = setHours;
	}
  
    
	public void setTeachingUnit(String setTeachingUnit) {
		this.TeachingUnit = setTeachingUnit;
	}
  

	
	public void setnameCourse(String setnameCourse) {
		this.nameCourse = setnameCourse;
	}
    
    public String findTeachingUnit(){
    	return String.valueOf(controllerTest.findTeachingUnit());
    }
	
	public String checksCourseDetails() {
		return String.valueOf(controllerTest.checksCourseDetails(nameCourse,nameCourse,Hours));
	}
  
	public String insertCourse() {
		return String.valueOf(controllerTest.insertCourse(TeachingUnit,nameCourse,Hours));
	}
    
	public void startController() {
		try {
			QueryController.connect("localhost", 5555);
		} catch (IOException e) {
			e.printStackTrace();
		}
		controllerTest = new SystemManagerAddCourseController("ControllerTestID");
		controllerTest.isNotTest = false;
	}
}