


/**
 * Generated by FITpro Fixture Generator
 */
package Fixtures.client;

import java.io.IOException;

import SystemManager.SystemManagerAddCourseController;
import SystemManager.SystemManagerAddPreCourseController;
import application.QueryController;
import fit.ActionFixture;

/*
 * TODO: modify class to match the FIT test - edit and add methods as required.
 */
public class DefineCourse extends ActionFixture {
	SystemManagerAddCourseController controllerTest;
	SystemManagerAddPreCourseController nextControllerTest;
	private String TeachingUnit;
	private String nameCourse;
	private String Hours;
	private String preCourse;
	public static boolean isNotTest = false;
	
	public void setHours(String setHours) {
		this.Hours = setHours;
	}
  
    
	public void setTeachingUnit(String setTeachingUnit) {
		this.TeachingUnit = setTeachingUnit;
	}
	
	public void setnameCourse(String setnameCourse) {
		this.nameCourse = setnameCourse;
	}
    
	public void setPreCourse(String preCourse) {
		this.preCourse = preCourse;
	}
	
    public String findTeachingUnit(){
    	return String.valueOf(controllerTest.findTeachingUnit());
    }
	
	public String checksCourseDetails() {
		return String.valueOf(controllerTest.checksCourseDetails(nameCourse,nameCourse,Hours));
	}
  
	public String insertCourse() {
		return String.valueOf(controllerTest.insertCourse(TeachingUnit,nameCourse,Hours));
	}
    
	
	public String insertPreCourse() {
		return String.valueOf(nextControllerTest.insertPreCourse(preCourse));
	}
	
	public void startController() {
		try {
			QueryController.connect("localhost", 5555);
		} catch (IOException e) {
			e.printStackTrace();
		}
		controllerTest = new SystemManagerAddCourseController("ControllerTestID");
		controllerTest.isNotTest = false;
	}
	
	public void startNextController() {
		nextControllerTest = new SystemManagerAddPreCourseController("ControllerTestID");
		nextControllerTest.isNotTest = false;
		nextControllerTest.setCourseID(controllerTest.lastCourse);//set current course id.
		nextControllerTest.preCourses(null);
	}
}